version: '2.1'

services:

  nginx-mailcow:
    labels:
      - traefik.enable=true
      - traefik.http.routers.moo.rule=Host(`${MAILCOW_HOSTNAME}`)      
      - traefik.http.routers.moo.tls.certresolver=myresolver       
      - traefik.http.services.moo.loadbalancer.server.port=80        
    networks:
      - traefik      
    
networks:
  traefik:
    external:
      name: traefik_network